### ISSUE TITLE
Program won't stay running

### ISSUE THREAD

**Issue by Dalps1215** [maxensas/xiletrade#10]
[XileTrade.log](https://github.com/maxensas/xiletrade/files/5976565/XileTrade.log)
Windows 10, I use Awakened PoE Trade normally, but closed it to test this out. I also use MercuryTrade, LabCompass, and Exilence Next. The issue is that the program opens and runs for about a minute, but then closes and I have to reopen it again.

UPDATE: Seems to have problems running alongside Mercurytrade. It works fine on its own, but as soon as MercuryTrade is running, Xiletrade closes and gives the error log posted above, saying it can't open the clipboard. Any way to get rid of this interference?

**Comment by maxensas** [comment]
Hi Dalps, welcome and thanks for your contribution.
I need to do some tests to find the best answer but you probably should try by disabling the auto whisper message feature which read the clipboard frequently,
Be aware, if you stack a lot of softwares, you can have issues with key bindings. 
Anyway, i will add a fix for this, Xiletrade should not stop working with this error in the future.

**Comment by maxensas** [comment]
Changes made in https://github.com/maxensas/xiletrade/releases/tag/v1.3.3
I will test soon if clipboard access works properly now with other running softwares.

**Comment by maxensas** [comment]
I have just observed how Xiletrade works jointly with MercuryTrade and have not encountered any issues with either.
Test conditions:
- Disable whisper helper from MercuryTrade (Xiletrade's one is in developement but better by far) and Enable auto whisper from Xiletrade.
- Enable incoming and outcoming trades in mercury.
- Using live search and whisper message (click and auto paste with xiletrade) when interested.
- Using bulk feature, buying currencies.
- Tests dones using official project (not forked)  :
https://github.com/Exslims/MercuryTrade/releases/tag/1.0.3.6

If you are experiencing new errors or crashes related to this subject, please create a new ticket and a detailed use case.

My advice related to softwares using incoming or outcoming message from Path of exile : Just do not use this kind of software because your path of exile account can get banned for using tool reading chat log from the game. GGG gave me that advice and i share. I don't work for them but I understand the stakes well.
