### ISSUE TITLE
"Search percent value" results to invalid searches

### ISSUE THREAD

**Issue by tgntr** [maxensas/xiletrade#11]
Ey! Saw this tool in TFT and I'm always curious in my search of that custom market-breaking price checking algorithm, so I did some clicks. 

There is a problem with the values scaling when applying that feature. As far as I figured, by default the tool is filtering the market on 100% of item mods and values, which often leaves me with no results, therefore no data to base my price check on. So when I start lowering the percent values, it divides to floating points and either trade API throws errors and we get empty lists or we end up with floating point value on cluster levels mod for example which also leads to empty responses. Doesn't look like a complex issue, besides basic numbers processing and rounding, the fix should require just a little debugging on game-limits level. Otherwise good UI, it's always nice to have self-explaining settings when you hover on them.

Let me know if you implement a fix, I would play with it some more.

Thanks

**Comment by maxensas** [comment]
Hi tgntr ! Thanks for your contribution and your feedback, it's appreciated. I will take a look and debug it soon. 
It can happen due to different cultures (where you are located/country & language used) : it's look like percent value feature give a ,(coma) instead of .(dot) for the floating variable while lowering/increasing values > resulting on a request error from official trade website. 
I will fix it for next release, not a big deal indeed. The UI will be refreshed a bit to be even more pleasant with PoE.
NOTE : The value percent feature > 80% to 120% is a good answer to decrease a bit your mod value and find equivalent on market but it's a half answer. The best would be to search by lowest value from the tier you have on each item mod. It require some more search and work from me but it's doable in a distant future.

**Comment by tgntr** [comment]
I'm familiar with the regional issues on Windows, but I have it on dot. Here is a quick demonstration

[https://imgur.com/a/m3LgxFZ](url)

**Comment by maxensas** [comment]
Ok, there is no bug on your example i see now : 
-On cluster jewels It's irrelevant to use search by percent value outside the explicits (suffix/prefix)
-Look your ench : 4.25 passives doesn't exist (it's set as minimum & maximum) 
.Tips about pricing medium clusters : with 4 min & 5 max passives OR with 6 min/max passives (nothing else)

I will add a fix and prevent enchantment values to move with "search percent values".

**Comment by maxensas** [comment]
I just found the issue which appeared problematic not just for cluster jewels. Enchantment mods can also be explicit and that was problematic when filling the Xiletrade form. It was a bug indeed. Fixed for next 1.4 release.

**Comment by maxensas** [comment]
Fixed int 1.4 release.
