### ISSUE TITLE
Bulk Exchange feature request : chaos equivalent per unit

### ISSUE THREAD

**Issue by zerger3** [maxensas/xiletrade#17]
Hi, thanks for the nice tool :)
could you add a way to display not only the ex price in chaos on top of the search results but also a column that calculates the ex price in chaos?

that would be a helpful way to determine if i buy 40 Fossils in bulk for 1 ex or if i get a better deal in chaos

thx

**Comment by maxensas** [comment]
Hello, there are several things to look at before, a simple answer is not possible for the moment but I obviously take into account any remark or element likely to add quality of life when using Xiletrade.

About the bulk exchange feature, as you will have noticed you have to select both currencies PAY and GET, I added this intentionally to avoid passive scams used (mostly) or not on POE beginners or clumsy. For example, with the main website currently: if you search for an item (currency) without mentioning the currency you want to sell, the trade website is likely to show prices in exa first and chaos after, and therefore do not necessarily display the most interesting prices first. The problem is also present for many other currencies, the bots use this weakness all the time. GGG's API isn't perfect and I'm sure developers are well aware of that. Let’s wait for the developers to improve their algorithms before laying a strong one that perfectly meets user needs, knowing full well that it will become obsolete for the next 12 months.

What I want is to offer a tool where you remove the burden of having to calculate without stopping to know what is the best plan for the exchange of such or such currencies. such as, for example, proposing a list of the most interesting to the least interesting sales using preferred currencies*, color codes without pytagora's theroeme calculation grids, archimedes push calculation when players simply want to kill mobs. You will understand, I want to offer a robust tool for end-game players (like me) and a tool that makes life easier for players who have little knowledge of the game and protects them from scams. 90% or more of poe players are not using any third party software and never go far into poe.

*Regarding preferred currencies, it must be understood that the orb of chaos and exa may not be considered overnight as the main currencies of exchange, keep that in mind. You only have to observe the evolution of the game over the past two years to realize it, I could go into much more detail but that's already a lot for an answer :)

The subject remains open for the moment, thank you for your suggestion.

**Comment by zerger3** [comment]
hmm i hope you get my idea, this is from the better trading extension for the normal trade site
![image](https://user-images.githubusercontent.com/3465525/123987925-e0e8bb00-d9c7-11eb-9af5-eef35d1eea38.png)

something like
![image](https://user-images.githubusercontent.com/3465525/123988843-a4698f00-d9c8-11eb-91e1-8ed093210d1b.png)

**Comment by maxensas** [comment]
By replying on the spot.

I fully understand your request and the tool will respond to this one at some point. 

Chaos equivalent price you see on this extension is fully based on poe.ninja rating and pretty easy for me to add this information for each line and each currency, but as a dev you need to think a little bit deeper and cover each point related to the subject:
- Shall i use poe.ninja rating or create my own ? I need to think about that.
- My poe.ninja addon need a technical update aswell (reduce the amount of request sent to poe.ninja website).
- Detail & Bulk listing actually need some rework. Surprise in a future release !
- Xiletrade must also allow compatibility for all languages (on the three POE releases: Global, Garena & Tencent) as it was designed in the beginning : That addon would only be usefull for Global release.
- Xiletrade window need to remain small to allow a good use with POE, maybe using tooltips ? I need to think.

This project is still young.

**Comment by maxensas** [comment]
After spending some time finding the best possible answer, I decided to use the information that poe.ninja offers. We therefore find the equivalents in chaos per unit and in addition we are entitled with an alert to know if the deal is good or not. No additional line seems necessary, another search by switching between chaos and exalt is enough to meet the expressed need. Enoy! :)
![eq1](https://user-images.githubusercontent.com/62154281/132956270-a7e24f16-f262-4bcc-876b-c016afc4f93f.png)
![eq2](https://user-images.githubusercontent.com/62154281/132956279-ac176353-3d38-47b3-b6db-8d888d37d41c.png)
![eq3](https://user-images.githubusercontent.com/62154281/132956282-db3f5f10-ea25-49d9-a49b-9ebdba431107.png)
![eq4](https://user-images.githubusercontent.com/62154281/132956284-d81e41d6-80b0-4a72-b68f-804f4d8e565f.png)

https://github.com/maxensas/xiletrade/releases/tag/1.6

**Comment by zerger3** [comment]
looks great :)
